export type ProductImage = {
  url: string;
  sourceUrl: string;
  alt: string;
  credit: string;
};

// Presentation-only media registry. Canonical product specifications remain in catalog shards.
// Remote manufacturer assets are intentionally allowed to fail gracefully in the UI.
export const productImages: Record<string, ProductImage> = {
  "mouse-superlight-2c": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight-2c-pdp/gallery/pro-x-superlight-2c-mouse-top-angle-offwhite-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/pro-x-superlight-2c",
    alt: "Logitech G PRO X SUPERLIGHT 2c gaming mouse",
    credit: "Logitech G official product image",
  },
  "mouse-gpx2": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight-2/new-gallery-assets-2025/pro-x-superlight-2-mice-top-angle-black-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/pro-x2-superlight-wireless-mouse.910-006628",
    alt: "Logitech G PRO X SUPERLIGHT 2 gaming mouse",
    credit: "Logitech G official product image",
  },
  "mouse-viper-v3-pro": {
    url: "https://assets2.razerzone.com/images/pnx.assets/474a68bae599387eb85e884c484e9ce3/sequence_00000.webp",
    sourceUrl: "https://www.razer.com/gaming-mice/razer-viper-v3-pro",
    alt: "Razer Viper V3 Pro gaming mouse",
    credit: "Razer official product image",
  },
  "mouse-op1w-4k-v2": {
    url: "https://endgamegear.com/cdn/shop/files/EGG-OP1w-4K-Black_top_down.-3000x3000-2567b33.jpg?v=1736862604&width=3000",
    sourceUrl: "https://endgamegear.com/products/op1w-4k-v2-wireless-gaming-mouse",
    alt: "Endgame Gear OP1w 4K v2 wireless gaming mouse viewed from above",
    credit: "Endgame Gear official product image",
  },
  "mouse-zowie-fk2-dw": {
    url: "https://image.benq.com/is/image/benqco/1-fk2-dw-top?%24ResponsivePreset%24=&fmt=png-alpha",
    sourceUrl: "https://zowie.benq.com/en-us/mouse/fk2-dw.html",
    alt: "ZOWIE FK2-DW wireless gaming mouse viewed from above",
    credit: "ZOWIE official product image",
  },
  "mouse-zowie-s2-dw": {
    url: "https://image.benq.com/is/image/benqco/1-s2-dw-top?%24ResponsivePreset%24=&fmt=png-alpha",
    sourceUrl: "https://zowie.benq.com/en-us/mouse/s2-dw.html",
    alt: "ZOWIE S2-DW wireless gaming mouse viewed from above",
    credit: "ZOWIE official product image",
  },
  "mouse-wallhack-m001": {
    url: "https://wallhack.com/cdn/shop/t/68/assets/wh-m001-hero.avif?v=138427762620322925981789136467",
    sourceUrl: "https://wallhack.com/en-fr/pages/campaigns/m-001",
    alt: "WALLHACK M-001 gaming mouse viewed from above",
    credit: "WALLHACK official product image",
  },
  "mouse-pro-x2-superstrike": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x2-superstrike-pdp/2026/pro-x2-superstrike-top-angle-lifestyle-gallery-2.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/pro-x2-superstrike-mouse.910-007700",
    alt: "Logitech G PRO X2 SUPERSTRIKE gaming mouse",
    credit: "Logitech G official product image",
  },
  "mouse-viper-v4-pro": {
    url: "https://dl.razerzone.com/src2/20779/20779-02-en-v1.png",
    sourceUrl: "https://mysupport.razer.com/app/answers/detail/a_id/20775/",
    alt: "Razer Viper V4 Pro gaming mouse in black and white",
    credit: "Razer official support image",
  },
  "mouse-wlmouse-beast-x-max": {
    url: "https://www.wlmouse.com/cdn/shop/files/max_6aaf780e-f0d8-4857-ae3e-e189612e6b28.jpg?v=1755482399&width=2000",
    sourceUrl: "https://www.wlmouse.com/products/beast-max",
    alt: "WLMOUSE Beast X Max magnesium gaming mouse",
    credit: "WLMOUSE official product image",
  },
  "mouse-lamzu-inca": {
    url: "https://lamzu.com/cdn/shop/files/INCA_800X800_1.jpg?v=1740597300",
    sourceUrl: "https://lamzu.com/collections/inca/products/lamzu-inca",
    alt: "LAMZU INCA wireless gaming mouse",
    credit: "LAMZU official product image",
  },
  "pad-logitech-pro-x-control": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-control-pdp/gallery/pro-x-control-mouse-pad-top-angle-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/pro-x-control-gaming-mousepad.943-001617",
    alt: "Logitech G PRO X CONTROL gaming mousepad",
    credit: "Logitech G official product image",
  },
  "pad-esptiger-sr-tang-dao": {
    url: "https://esptiger.com/cdn/shop/files/ET-MP-TANGDAO-SR-ORANGE_1_49241cdf-a24f-46e3-86ad-4ea9c21bd28e.webp?v=1709007355&width=1946",
    sourceUrl: "https://esptiger.com/products/sr-tang-dao-balance-gaming-mousepad",
    alt: "ESPTIGER SR Tang Dao orange gaming mousepad",
    credit: "ESPTIGER official product image",
  },
  "pad-esptiger-lei-ling": {
    url: "https://esptiger.com/cdn/shop/products/2_7edfb364-50de-45c3-8fc0-549e9753dadb.webp?v=1705364922&width=1946",
    sourceUrl: "https://esptiger.com/products/lei-ling-balance-gaming-mousepad",
    alt: "ESPTIGER Lei Ling gaming mousepad",
    credit: "ESPTIGER official product image",
  },
  "keyboard-wooting-60he-v2": {
    url: "https://wooting.io/_next/image?q=90&url=https%3A%2F%2Fwooting-website.ams3.cdn.digitaloceanspaces.com%2Fproducts%2Fkeyboards%2F60HEv2%2F60he-v2_og-and-split.webp&w=3840",
    sourceUrl: "https://wooting.io/wooting-60he-v2",
    alt: "Wooting 60HE v2 regular and split-spacebar keyboards",
    credit: "Wooting official product image",
  },
  "keyboard-logitech-g512-x-75": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/g512-x-75-98-pdp/g512-x-75/gallery/g512-x-75-black-top-angle-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/g512-x-75-gaming-keyboard",
    alt: "Logitech G G512 X 75 TMR analog mechanical gaming keyboard",
    credit: "Logitech G official product image",
  },
  "keyboard-rog-falchion-ace-75-he": {
    url: "https://dlcdnwebimgs.asus.com/files/media/202511/4cfcf855-ca9a-45ec-a2bc-c533d8865305/v1/img/kv.jpg",
    sourceUrl: "https://rog.asus.com/us/keyboards/keyboards/compact/rog-falchion-ace-75-he/",
    alt: "Black and white ASUS ROG Falchion Ace 75 HE gaming keyboards",
    credit: "ASUS ROG official product image",
  },
  "keyboard-nuphy-field75-he-v2": {
    url: "https://pay.nuphy.com/cdn/shop/files/Field75_V2_HE_v3_f5f5f5_800x.webp?v=1775816795",
    sourceUrl: "https://pay.nuphy.com/products/nuphy-field75-he-v2-1",
    alt: "NuPhy Field75 HE V2 magnetic gaming keyboard",
    credit: "NuPhy official product image",
  },
  "keyboard-melgeek-made68-pro-plus": {
    url: "https://cdn.shopify.com/s/files/1/0078/2863/5712/files/MelGeek_MADE68_Pro_gaming_keyboard_1.jpg?v=1782373870",
    sourceUrl: "https://www.melgeek.com/products/made68-pro",
    alt: "MelGeek MADE68 Pro Plus Hall-effect gaming keyboard",
    credit: "MelGeek official product image",
  },
  "switch-gateron-magnetic-jade-pro": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2512/30/products/gateron-magnetic-jade-pro-switch-magnetic-hallsensor-switch-mechanical-keyboard-wooting.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-pro-switch-set",
    alt: "Gateron Magnetic Jade Pro Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-magnetic-jade-silent": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2605/15/products/gateron-magnetic-jade-silent-switch1.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-silent-switch-set",
    alt: "Gateron Magnetic Jade Silent Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-jade-attraction": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2604/10/products/gateron-magnetic-jade-attraction-he-switch9-143504c316.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-attraction-he-switch-set",
    alt: "Gateron Magnetic Jade Attraction Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-magnetic-black-lotus": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2609/10/photo/gateron-magnetic-black-lotus-switch-set71.webp",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-black-lotus-he-switch-set",
    alt: "Gateron Magnetic Black Lotus Hall-effect switch set",
    credit: "Gateron official product image",
  },
  "switch-gateron-low-profile-magnetic-jade-pro": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2411/14/products/bbfdabdb8f.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-full-pom-low-profile-magnetic-jade-pro-switch-set",
    alt: "Gateron Full POM Low Profile Magnetic Jade Pro Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-geon-raw-he-40gf": {
    url: "https://geon.works/cdn/shop/files/115588790244153042_403743789.jpg?v=1714532073&width=1445",
    sourceUrl: "https://geon.works/products/geon-raw-he-switch",
    alt: "GEONWORKS Raw Hall-effect switch",
    credit: "GEONWORKS official product image",
  },
  "switch-geon-strike-he": {
    url: "https://geon.works/cdn/shop/files/GMI01671.jpg?v=1784099603&width=416",
    sourceUrl: "https://geon.works/products/strike-he-switch",
    alt: "GEONWORKS Strike HE clicky Hall-effect switch",
    credit: "GEONWORKS official product image",
  },
  "mouse-op1-8k-v2": {
    url: "https://endgamegear.com/cdn/shop/files/OP1_Black_top_down.jpg?v=1736944464&width=2499",
    sourceUrl: "https://endgamegear.com/products/op1-8k-v2-wired-gaming-mouse",
    alt: "Endgame Gear OP1 8K v2 wired gaming mouse viewed from above",
    credit: "Endgame Gear official product image",
  },
  "mouse-zowie-za13-dw": {
    url: "https://image.benq.com/is/image/benqco/1-za13-dw-top?%24ResponsivePreset%24=&fmt=png-alpha",
    sourceUrl: "https://zowie.benq.com/en-us/mouse/za13-dw.html",
    alt: "ZOWIE ZA13-DW wireless gaming mouse viewed from above",
    credit: "ZOWIE official product image",
  },
  "keyboard-pulsar-es-he-70": {
    url: "https://us.pulsar.gg/cdn/shop/files/Pulsar-eS-HE-70_ANSI-front1-ANSI_4dd1a65d-86f0-45db-987a-94be9671ff57_large.png?v=1755065886",
    sourceUrl: "https://us.pulsar.gg/products/ansi-es-he-70-gaming-keyboard",
    alt: "Pulsar eS HE 70 Hall-effect gaming keyboard in black",
    credit: "Pulsar official product image",
  },
  "switch-gateron-magnetic-jade-gaming": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2411/21/photo/GATERONMagicJadeSwitchKS-20MagneticHallSensorSwitch1.png",
    sourceUrl: "https://www.gateron.com/blog/detail/gateron-magnetic-switches-series-for-the-ultimate-gaming-experience",
    alt: "Gateron Magnetic Jade Gaming Hall-effect switch",
    credit: "Gateron official product image",
  }
  "mouse-beast-x-pro": {
    url: "https://www.wlmouse.com/cdn/shop/files/beastx.jpg?v=1755482362&width=2000",
    sourceUrl: "https://www.wlmouse.com/products/x-pro",
    alt: "WLMOUSE Beast X Pro gaming mouse",
    credit: "WLMOUSE official product image",
  },
  "mouse-x2-crazylight-mini": {
    url: "https://us.pulsar.gg/cdn/shop/files/X2_CrazyLight_LA-Gaming-Mouse-001_large.png?v=1758766896",
    sourceUrl: "https://us.pulsar.gg/products/x2-crazylight-la-gaming-mouse",
    alt: "Pulsar X2 CrazyLight Mini gaming mouse",
    credit: "Pulsar official product image",
  },
  "mouse-deathadder-v4-pro": {
    url: "https://assets3.razerzone.com/VuoDC-AaOZh-67auUdz2cfLwhgg=/1920x1280/https%3A%2F%2Fmedias-p1.phoenix.razer.com%2Fsys-master-phoenix-images-container%2Fh01%2Fhf3%2F9926511951902%2Fdeathadder-v4-pro-black-500x500.png",
    sourceUrl: "https://www.razer.com/gaming-mice/razer-deathadder-v4-pro",
    alt: "Razer DeathAdder V4 Pro gaming mouse",
    credit: "Razer official product image",
  },
  "mouse-g502-x-plus": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/g502x-plus/2026-update/gallery/g502-x-plus-top-angle-black-purple-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/g502-x-plus-wireless-lightforce",
    alt: "Logitech G G502 X PLUS wireless gaming mouse",
    credit: "Logitech G official product image",
  },
  "mouse-naga-v2-pro": {
    url: "https://assets3.razerzone.com/0BTnfDndkuUtHnVK3MKm8F39AGw=/1920x1280/https%3A%2F%2Fmedias-p1.phoenix.razer.com%2Fsys-master-phoenix-images-container%2Fhb2%2Fhb9%2F9529652379678%2Fnaga-v2-pro-2-500x500.png",
    sourceUrl: "https://www.razer.com/gaming-mice/razer-naga-v2-pro",
    alt: "Razer Naga V2 Pro MMO gaming mouse",
    credit: "Razer official product image",
  },
  "mouse-scimitar-se": {
    url: "https://assets.corsair.com/image/upload/c_pad%2Cq_85%2Ch_1100%2Cw_1100%2Cf_auto/products/Gaming-Mice/base-scimitar-elite-se-config/CH-9314014-WW/CH-9314014-WW_01.webp",
    sourceUrl: "https://www.corsair.com/us/en/p/gaming-mouse/ch-9314014-ww/scimitar-elite-wireless-se-mmo-gaming-mouse-gun-metal-ch-9314014-ww",
    alt: "Corsair SCIMITAR ELITE WIRELESS SE MMO gaming mouse",
    credit: "Corsair official product image",
  },
  "mouse-zowie-u2-dw": {
    url: "https://image.benq.com/is/image/benqco/U2-DW_top?%24ResponsivePreset%24=&fmt=png-alpha",
    sourceUrl: "https://zowie.benq.com/en-us/mouse/u2-dw.html",
    alt: "ZOWIE U2-DW wireless gaming mouse viewed from above",
    credit: "ZOWIE official product image",
  },
  "mouse-zowie-ec2-dw": {
    url: "https://image.benq.com/is/image/benqco/ec2-dw-top?%24ResponsivePreset%24=&fmt=png-alpha",
    sourceUrl: "https://zowie.benq.com/en-us/mouse/ec2-dw.html",
    alt: "ZOWIE EC2-DW wireless gaming mouse viewed from above",
    credit: "ZOWIE official product image",
  },
  "mouse-xm2w-4k-v2": {
    url: "https://endgamegear.com/cdn/shop/files/EGG-XM2w-4k_BLK_top_down-3000x3000-2567b33_1.jpg?v=1736945917&width=2019",
    sourceUrl: "https://endgamegear.com/products/xm2w-4k-v2-wireless-gaming-mouse",
    alt: "Endgame Gear XM2w 4k v2 wireless gaming mouse viewed from above",
    credit: "Endgame Gear official product image",
  },
  "mouse-vaxee-xe-v2": {
    url: "https://www.vaxee.co/JP/data/goods/gallery/202507/1751876579739119958.png",
    sourceUrl: "https://www.vaxee.co/en/product.php?act=view&id=271",
    alt: "VAXEE XE v2 Wireless gaming mouse",
    credit: "VAXEE official product image",
  },
  "mouse-lamzu-maya-x": {
    url: "https://lamzu.com/cdn/shop/files/Maya_X_8K_800X800_1-797429.jpg?v=1729079319",
    sourceUrl: "https://lamzu.com/products/lamzu-maya-x",
    alt: "LAMZU MAYA X 8K wireless gaming mouse",
    credit: "LAMZU official product image",
  },
  "mouse-ulx-competition-medium": {
    url: "https://finalmouse.com/cdn/shop/files/web2.png?v=1737785210&width=450",
    sourceUrl: "https://finalmouse.com/pages/mice",
    alt: "Finalmouse UltralightX Competition gaming mouse",
    credit: "Finalmouse official product image",
  },
  "mouse-x2h-crazylight-medium": {
    url: "https://us.pulsar.gg/cdn/shop/files/Pulsar-X2H_medium_black_front-medium_large.png?v=1767868622",
    sourceUrl: "https://us.pulsar.gg/products/x2h-crazylight-medium-gaming-mouse",
    alt: "Pulsar X2H CrazyLight Medium gaming mouse",
    credit: "Pulsar official product image",
  },
  "mouse-rog-harpe-ii-ace": {
    url: "https://dlcdnwebimgs.asus.com/gain/5F8A9BE6-C335-48FF-8D54-023F84885525/w1000/h732",
    sourceUrl: "https://rog.asus.com/us/mice-mouse-pads/mice/wireless/rog-harpe-ii-ace/gallery/",
    alt: "ASUS ROG Harpe II Ace wireless gaming mouse",
    credit: "ASUS ROG official product image",
  },
  "mouse-rog-keris-ii-ace": {
    url: "https://dlcdnwebimgs.asus.com/gain/9B783ACB-999D-41F3-AC55-7859FB30C90B/w717/h525/fwebp",
    sourceUrl: "https://rog.asus.com/us/mice-mouse-pads/mice/wireless/rog-keris-ii-ace/",
    alt: "ASUS ROG Keris II Ace wireless gaming mouse",
    credit: "ASUS ROG official product image",
  },
  "mouse-corsair-sabre-v2-pro-mg": {
    url: "https://assets.corsair.com/image/upload/c_pad%2Cq_85%2Ch_1100%2Cw_1100%2Cf_auto/products/Gaming-Mice/base-sabre-v2-mg-config/gallery/sabre_v2_pro_wl_mg_blk_01.webp",
    sourceUrl: "https://www.corsair.com/us/en/p/gaming-mouse/ch-931g100-ww/sabre-v2-pro-wireless-magnesium-alloy-gaming-mouse-black-ch-931g100-ww",
    alt: "Corsair SABRE v2 PRO Wireless Magnesium gaming mouse",
    credit: "Corsair official product image",
  },
  "mouse-burst-ii-air": {
    url: "https://cdn.shopify.com/s/files/1/0556/5795/5430/files/2-TB-BurstIIAir-BLK.png?crop=center&height=1000&v=1713206432&width=1000",
    sourceUrl: "https://www.turtlebeach.com/products/burst-ii-air-mouse",
    alt: "Turtle Beach Burst II Air wireless gaming mouse",
    credit: "Turtle Beach official product image",
  },
  "mouse-basilisk-v3-pro-35k": {
    url: "https://assets3.razerzone.com/QrFFO4KLgcSlv8V4Zhksri9dTK8=/1920x1280/https%3A%2F%2Fmedias-p1.phoenix.razer.com%2Fsys-master-phoenix-images-container%2Fh5a%2Fh1c%2F9821720576030%2Fbasilisk-v3-pro-35k-500x500.png",
    sourceUrl: "https://www.razer.com/gaming-mice/razer-basilisk-v3-pro-35k",
    alt: "Razer Basilisk V3 Pro 35K wireless gaming mouse",
    credit: "Razer official product image",
  },
  "mouse-gpx2-dex": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight-2-dex/gallery/new-gallery-assets-2025/pro-x-superlight-2-dex-mouse-top-angle-black-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-gb/products/gaming-mice/pro-x-superlight-2-dex.910-007358.html",
    alt: "Logitech G PRO X SUPERLIGHT 2 DEX gaming mouse",
    credit: "Logitech G official product image",
  },
  "mouse-logitech-g309": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/G309-Lightspeed-Gaming-Mouse/gallery/g309-lightspeed-wireless-mouse-white-gallery-1.png",
    sourceUrl: "https://www.logitechg.com/en-us/shop/p/g309-lightspeed-gaming-mouse.910-007205",
    alt: "Logitech G G309 LIGHTSPEED wireless gaming mouse",
    credit: "Logitech G official product image",
  },
  "mouse-kone-ii-air": {
    url: "https://cdn.shopify.com/s/files/1/0668/2991/0264/files/US_INTL_Gallery_Image_Thumbnail_KONE_II_AIR_Black_02.png?crop=center&height=1000&v=1722435745&width=1000",
    sourceUrl: "https://www.turtlebeach.com/products/kone-ii-air-mouse",
    alt: "Turtle Beach Kone II Air wireless gaming mouse",
    credit: "Turtle Beach official product image",
  },
  "mouse-hitscan-hyperlight": {
    url: "https://hitscan.com/cdn/shop/files/HITSCAN_HYPERLIGHT_BLACK_1.png?v=1734198922&width=2048",
    sourceUrl: "https://hitscan.com/products/hyperlight",
    alt: "Hitscan Hyperlight wireless gaming mouse",
    credit: "Hitscan official product image",
  },
  "mouse-wlmouse-ying": {
    url: "https://www.wlmouse.com/cdn/shop/files/WLMOUSE_Ying_MG_Gaming_Mouse_Black.jpg?v=1782974985&width=2000",
    sourceUrl: "https://www.wlmouse.com/products/yingmg",
    alt: "WLMOUSE YING magnesium gaming mouse",
    credit: "WLMOUSE official product image",
  },
  "mouse-akitsu-small": {
    url: "https://www.finemax.gg/cdn/shop/files/713ECA29-89CC-448F-B806-17B7D416BA2D.jpg?v=1727595207&width=1946",
    sourceUrl: "https://www.finemax.gg/vi/products/carbon-fibre-mouse",
    alt: "Arbiter Studio AKITSU Small carbon-fiber gaming mouse",
    credit: "FineMax Gears product image",
  },
  "mouse-akitsu-medium": {
    url: "https://arbiterstudio.com/cdn/shop/files/Arbiter_Studio_AKITSU_Carbon_Fiber_8K_Wireless_Gaming_Mouse_main.webp?v=1770346470&width=1780",
    sourceUrl: "https://arbiterstudio.com/products/tenko-akitsu-medium-40g-carbon-fiber-8k-wireless-gaming-mouse",
    alt: "Arbiter Studio AKITSU Medium carbon-fiber gaming mouse",
    credit: "Arbiter Studio official product image",
  },
  "mouse-pulsar-xlite-v4": {
    url: "https://www.pulsar.gg/cdn/shop/files/PulsarXlitev4GamingMouse_Black_001_large.png?v=1720400926",
    sourceUrl: "https://www.pulsar.gg/products/xlite-v4-gaming-mouse",
    alt: "Pulsar Xlite v4 Medium ergonomic gaming mouse",
    credit: "Pulsar official product image",
  },
  "mouse-pulsar-x3": {
    url: "https://www.pulsar.gg/cdn/shop/files/Pulsar-X3-Gaming-Mouse_Black_001_kr_large.png?v=1758612507",
    sourceUrl: "https://www.pulsar.gg/products/x3-rhd-gaming-mouse",
    alt: "Pulsar X3 Medium gaming mouse",
    credit: "Pulsar official product image",
  },
  "mouse-mchose-l7-pro": {
    url: "https://www.mchose.store/cdn/shop/files/mchose-official-mouse-l7-white-mchose-l7-series-ultra-lightweight-wireless-gaming-mouse-1166639712.jpg?v=1754474334&width=2000",
    sourceUrl: "https://www.mchose.store/products/mchose-l7-series-ultra-lightweight-wireless-gaming-mouse",
    alt: "MCHOSE L7 Pro ultra-light wireless gaming mouse",
    credit: "MCHOSE official product image",
  },
  "mouse-viper-v3-pro-se": {
    url: "https://assets3.razerzone.com/mZOqhW0m3rPbh6sBqEZ1ItWOSNE=/1920x1280/https%3A%2F%2Fmedias-p1.phoenix.razer.com%2Fsys-master-phoenix-images-container%2Fh55%2Fh10%2F10011389198366%2Fviper-v3-pro-se-500x500.png",
    sourceUrl: "https://www.razer.com/gaming-mice/razer-viper-v3-pro-se",
    alt: "Razer Viper V3 Pro SE gaming mouse",
    credit: "Razer official product image",
  },
  "mouse-vaxee-xe-s-wireless-4k": {
    url: "https://www.vaxee.co/EN/data/goods/gallery/202405/1715938000380164487.png",
    sourceUrl: "https://www.vaxee.co/en/product.php?act=view&id=227",
    alt: "VAXEE XE-S Wireless 4K gaming mouse",
    credit: "VAXEE official product image",
  },
  "keyboard-wooting-80he-plus": {
    url: "https://wooting.io/_next/image?q=90&url=https%3A%2F%2Fwooting-website.ams3.cdn.digitaloceanspaces.com%2Fproducts%2Fkeyboards%2F80HE-plus%2Fprebuilt-images%2Fhero%2F80heplus-hero.webp&w=3840",
    sourceUrl: "https://wooting.io/wooting-80he-plus",
    alt: "Wooting 80HE+ Hall-effect gaming keyboard",
    credit: "Wooting official product image",
  },
  "keyboard-razer-huntsman-v3-pro-tkl-8khz": {
    url: "https://assets3.razerzone.com/iajuRCuAMNuncojOMjSjzRZzBNY=/1920x1280/https%3A%2F%2Fmedias-p1.phoenix.razer.com%2Fsys-master-phoenix-images-container%2Fhb9%2Fh24%2F9980311076894%2Fhuntsman-v3-pro-tkl-8khz-b-500x500.png",
    sourceUrl: "https://mysupport.razer.com/app/answers/detail/a_id/19797/~/razer-huntsman-v3-pro-tenkeyless-8-khz-%7C-rz03-0552-support-%26-faqs",
    alt: "Razer Huntsman V3 Pro Tenkeyless 8KHz gaming keyboard",
    credit: "Razer official product image",
  },
  "keyboard-keychron-q1-he-8k": {
    url: "https://mechanicalkeyboards.com/cdn/shop/files/26789-BL5V4-Keychron-Q1-HE-8K-White-Aluminum-75-Hotswap-RGB-Keyboard.jpg?v=1765904769&width=750",
    sourceUrl: "https://mechanicalkeyboards.com/products/keychron-q1-he-8k-aluminum-75-hotswap-rgb-keyboard",
    alt: "Keychron Q1 HE 8K magnetic gaming keyboard",
    credit: "MechanicalKeyboards product image",
  },
  "keyboard-keychron-q3-he-8k": {
    url: "https://mechanicalkeyboards.com/cdn/shop/files/26793-M9912-Keychron-Q3-HE-8K-Aluminum-TKL-Hotswap-RGB-Keyboard.jpg?v=1766079787&width=2400",
    sourceUrl: "https://mechanicalkeyboards.com/products/keychron-q3-he-8k-aluminum-tkl-hotswap-rgb-keyboard",
    alt: "Keychron Q3 HE 8K magnetic TKL gaming keyboard",
    credit: "MechanicalKeyboards product image",
  },
  "keyboard-keychron-k2-he-tmr-v1": {
    url: "https://cdn.shopify.com/s/files/1/0568/8514/9779/files/K2-HE-10.jpg?v=1726825696",
    sourceUrl: "https://www.keychron.com/products/keychron-k2-he-wireless-magnetic-switch-keyboard",
    alt: "Keychron K2 HE wireless magnetic keyboard",
    credit: "Keychron official product image",
  },
  "keyboard-logitech-pro-x2-rapid": {
    url: "https://resource.logitechg.com/w_544%2Ch_466%2Car_7%3A6%2Cc_pad%2Cq_auto%2Cf_auto%2Cdpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x2-rapid-pdp/gallery/pro-x2-rapid-black-gallery1.png",
    sourceUrl: "https://www.logitechg.com/en-ca/shop/p/pro-x2-rapid",
    alt: "Logitech G PRO X2 RAPID magnetic gaming keyboard",
    credit: "Logitech G official product image",
  },
  "switch-gateron-magnetic-jade-emerald": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2512/30/products/gateron-magnetic-jade-emerald-he-switch.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-emerald-switch-set",
    alt: "Gateron Magnetic Jade Emerald Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-cherry-mx2a-red": {
    url: "https://www.cherry.de/fileadmin/_processed_/7/a/csm_6f9d95492f1c7d13592741ed63d263d1_bef242fb90.jpg",
    sourceUrl: "https://www.cherry.de/en-us/product/mx2a-red",
    alt: "CHERRY MX2A Red mechanical switch",
    credit: "CHERRY official product image",
  },
  "switch-wooting-lekker-tikken-medium": {
    url: "https://checkout-row.wooting.io/cdn/shop/files/lekker-tikken_SW1-TIK-MID-20P_1.jpg?v=1769428059&width=1445",
    sourceUrl: "https://wooting.io/product/wooting-lekker-tikken-medium-switch",
    alt: "Wooting Lekker Tikken Medium Hall-effect switch",
    credit: "Wooting official product image",
  },
  "switch-wooting-lekker-v2-l45": {
    url: "https://checkout-row-apac.wooting.io/cdn/shop/files/L45-V2.png?v=1771508596&width=1445",
    sourceUrl: "https://wooting.io/product/lekker-switch-l45-v2",
    alt: "Wooting Lekker V2 L45 Hall-effect switch",
    credit: "Wooting official product image",
  },
  "switch-wooting-lekker-v2-l60": {
    url: "https://checkout-row.wooting.io/cdn/shop/files/L60-V2.png?v=1771514434&width=1445",
    sourceUrl: "https://wooting.io/product/lekker-switch-l60-v2",
    alt: "Wooting Lekker V2 L60 Hall-effect switch",
    credit: "Wooting official product image",
  },
  "switch-gateron-magnetic-jade-delta-light": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2511/08/products/GATERONMagneticJadeDeltaSwitch1.png?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-delta-switch",
    alt: "Gateron Magnetic Jade Delta Light Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-magnetic-jade-delta-dark": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2511/08/products/GATERONMagneticJadeDeltaSwitch7.png?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-delta-switch",
    alt: "Gateron Magnetic Jade Delta Dark Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-magnetic-genty-silent": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2512/30/products/gateron-magnetic-genty-silent-he-switch.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-genty-silent-switch",
    alt: "Gateron Magnetic Genty Silent Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-magnetic-jade-ruby": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2512/30/products/gateron-magnetic-jade-ruby-switch1.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-ruby-switch",
    alt: "Gateron Magnetic Jade Ruby Hall-effect switch",
    credit: "Gateron official product image",
  },
  "switch-gateron-magnetic-jade-max": {
    url: "https://ueeshop.ly200-cdn.com/u_file/UPAW/UPAW819/2512/30/products/gateron-mangeitc-jade-max-switch.webp?x-oss-process=image%2Fresize%2Cm_lfit%2Ch_1000%2Cw_1000%2Fquality%2Cq_100",
    sourceUrl: "https://www.gateron.com/products/gateron-magnetic-jade-max-switch-set",
    alt: "Gateron Magnetic Jade Max Hall-effect switch",
    credit: "Gateron official product image",
  },
};

export const imageForProduct = (productId: string) => productImages[productId];
